---
- hosts: all
  become: true
  tasks:
  - name: repo update 
    apt:
      update-cache: yes
      cache_valid_time: 3600
  - name: installing package glances
    apt:
      name: glances
      state: present
       
      
      
      
