---
#simple playbook example for installing multiple packages tested on Debian 8 with Ansible 2.2
- hosts: all
  become: true
  tasks:
  - name: repo update 
    apt:
      update-cache: yes
      cache_valid_time: 3600
  - name: installing packages from the list
    apt: 
      name:
      - emacs-nox
      - python3
      - python-pip
      - htop
      - glances
      - nload
      state: present
