--- 
- hosts: all 
  remote_user: pionek 
  tasks: 
  - name: installing apache2 
    apt: 
      name: apache2
      update_cache: yes
      state: latest 
    become: True 
  - name: Check that apache2 service is enabled and running 
    service: 
      name: apache2
      state: started 
      enabled: True 
    become: True 

