--- 
- hosts: all 
  remote_user: pionek 
  tasks: 
  - name: Check that apache2 package is installed 
    apt: 
      name: apache2 
      state: present 
    become: True 
  - name: Stop the apache2 service 
    service: 
      name: apache2
      state: stopped 
    become: True 
  
