--- 
- hosts: all 
  remote_user: pionek 
  tasks: 
  - name: Ensure the apache2 package is installed 
    apt: 
      name: apache2 
      state: present 
    become: True 
  - name: start the apache2 service 
    service: 
      name: apache2
      state: started 
    become: True 
  
